-- =====================================================================
-- Synthetic seed data for customers, orders, and products (Snowflake)
-- Generated rows: 30 customers, 32 products, 57 orders
-- All data is fictional and generated for testing/demo purposes only.
-- =====================================================================
-- switch databse to semi_stracture_db
USE DATABASE SEMI_STRUCTURED_DB;

-- switch to correct schema staging
USE SCHEMA STAGING ;

-- ---------------------------------------------------------------------
-- CUSTOMERS
-- ---------------------------------------------------------------------


-- Corrected customer seed data for Snowflake
-- Converted VALUES(..., PARSE_JSON(...)) to INSERT ... SELECT ... PARSE_JSON(...)
-- Records: 30

USE DATABASE SEMI_STRUCTURED_DB;
USE SCHEMA STAGING;

INSERT INTO customers (customer_id, customer_name, customer_data)
SELECT 1001, 'Abigail O''Brien', PARSE_JSON('{"profile": {"first_name": "Abigail", "last_name": "O''Brien", "email": "abigail.obrien75@gmail.com", "loyalty_tier": "gold", "join_date": "2024-08-26", "is_active": true, "account_balance": 454.85, "lifetime_value": 1756.85, "birth_date": "1967-03-03", "gender": "male"}, "address": {"street": "1496 Pine Rd", "city": "Vancouver", "zip": "1968", "country": "Canada", "type": "shipping", "state": "BC", "coordinates": {"lat": 49.2958, "lng": -123.1124}}, "preferences": {"newsletter_opt_in": false, "preferred_language": "pt", "preferred_currency": "CAD", "marketing_channels": [], "notification_settings": {"email": true, "sms": false, "push": true}}, "devices": [{"device_id": "DEV-251262", "device_type": "desktop", "os": "Linux", "last_login": "2026-06-16T18:19:00Z", "is_trusted": true}, {"device_id": "DEV-289505", "device_type": "tablet", "os": "iPadOS", "last_login": "2026-08-14T18:40:00Z", "is_trusted": false}]}');
INSERT INTO customers (customer_id, customer_name, customer_data)
SELECT 1002, 'Sophia Jones', PARSE_JSON('{"profile": {"first_name": "Sophia", "last_name": "Jones", "email": "sophia.jones509@icloud.com", "loyalty_tier": "gold", "join_date": "2024-06-21", "is_active": true, "account_balance": 461.72, "lifetime_value": 2924.58, "phone": "+1-384-915-4999", "gender": "non-binary"}, "address": {"street": "8614 Lake Blvd", "city": "Los Angeles", "zip": "68829", "country": "USA", "type": "billing", "state": "CA", "coordinates": {"lat": 34.0095, "lng": -118.2425}}, "preferences": {"newsletter_opt_in": false, "preferred_language": "fr", "preferred_currency": "EUR", "marketing_channels": ["postal_mail", "email", "push"], "notification_settings": {"email": true, "sms": false, "push": true}}, "devices": [{"device_id": "DEV-829070", "device_type": "desktop", "os": "macOS", "last_login": "2026-08-16T15:37:00Z", "is_trusted": true}, {"device_id": "DEV-980770", "device_type": "mobile", "os": "iOS", "last_login": "2026-07-05T15:44:00Z", "is_trusted": true}]}');
INSERT INTO customers (customer_id, customer_name, customer_data)
SELECT 1003, 'Noah Martin', PARSE_JSON('{"profile": {"first_name": "Noah", "last_name": "Martin", "email": "noah.martin396@outlook.com", "loyalty_tier": "bronze", "join_date": "2022-08-06", "is_active": true, "account_balance": 177.73, "lifetime_value": 4906.81, "phone": "+1-423-986-5709", "gender": "male"}, "address": {"street": "6529 River Rd", "city": "Berlin", "zip": "2320", "country": "Germany", "type": "shipping", "coordinates": {"lat": 52.5583, "lng": 13.4369}}, "preferences": {"newsletter_opt_in": true, "preferred_language": "fr", "preferred_currency": "CAD", "marketing_channels": ["postal_mail", "email"], "notification_settings": {"email": false, "sms": false, "push": false}}, "devices": [{"device_id": "DEV-608520", "device_type": "mobile", "os": "iOS", "last_login": "2026-07-04T09:00:00Z", "is_trusted": false}]}');
INSERT INTO customers (customer_id, customer_name, customer_data)
SELECT 1004, 'Sean White', PARSE_JSON('{"profile": {"first_name": "Sean", "last_name": "White", "email": "sean.white708@gmail.com", "loyalty_tier": "platinum", "join_date": "2026-05-06", "is_active": true, "account_balance": 389.98, "lifetime_value": 7002.38, "phone": "+1-601-607-7536", "birth_date": "1970-08-19", "gender": null}, "address": {"street": "6570 Maple Ave", "city": "Denver", "zip": "18827", "country": "USA", "type": "shipping", "state": "CO", "coordinates": {"lat": 39.7002, "lng": -104.9802}}, "preferences": {"newsletter_opt_in": false, "preferred_language": "pt", "preferred_currency": "EUR", "marketing_channels": [], "notification_settings": {"email": true, "sms": true, "push": false}}, "devices": [{"device_id": "DEV-494505", "device_type": "tablet", "os": "iPadOS", "last_login": "2026-08-21T08:22:00Z", "is_trusted": true}]}');
INSERT INTO customers (customer_id, customer_name, customer_data)
SELECT 1005, 'Jose Davis', PARSE_JSON('{"profile": {"first_name": "Jose", "last_name": "Davis", "email": "jose.davis478@icloud.com", "loyalty_tier": "platinum", "join_date": "2025-10-05", "is_active": true, "account_balance": 72.06, "lifetime_value": 6009.91, "phone": "+1-690-908-3645", "birth_date": "1986-11-23", "gender": "male"}, "address": {"street": "8664 Highland Ave", "city": "Houston", "zip": "81194", "country": "USA", "type": "shipping", "state": "TX", "coordinates": {"lat": 29.7402, "lng": -95.3555}}, "preferences": {"newsletter_opt_in": false, "preferred_language": "fr", "preferred_currency": "AUD", "marketing_channels": ["sms", "postal_mail"], "notification_settings": {"email": true, "sms": false, "push": true}}, "devices": [{"device_id": "DEV-333876", "device_type": "tablet", "os": "iPadOS", "last_login": "2026-07-01T12:47:00Z", "is_trusted": true}, {"device_id": "DEV-642783", "device_type": "mobile", "os": "Android", "last_login": "2026-07-16T23:01:00Z", "is_trusted": true}]}');
INSERT INTO customers (customer_id, customer_name, customer_data)
SELECT 1006, 'Henry Nguyen', PARSE_JSON('{"profile": {"first_name": "Henry", "last_name": "Nguyen", "email": "henry.nguyen620@outlook.com", "loyalty_tier": "platinum", "join_date": "2022-02-01", "is_active": true, "account_balance": 361.56, "lifetime_value": 2828.68, "phone": "+1-282-425-2673", "gender": "male"}, "address": {"street": "5543 Sunset Rd", "city": "Austin", "zip": "91797", "country": "USA", "type": "shipping", "state": "TX", "coordinates": {"lat": 30.2825, "lng": -97.7131}}, "preferences": {"newsletter_opt_in": false, "preferred_language": "en", "preferred_currency": "CAD", "marketing_channels": ["postal_mail"], "notification_settings": {"email": true, "sms": false, "push": true}}, "devices": []}');
INSERT INTO customers (customer_id, customer_name, customer_data)
SELECT 1007, 'Matthew Young', PARSE_JSON('{"profile": {"first_name": "Matthew", "last_name": "Young", "email": "matthew.young743@yahoo.com", "loyalty_tier": "silver", "join_date": "2025-03-03", "is_active": true, "account_balance": 13.77, "lifetime_value": 4746.96, "phone": "+1-871-349-8771", "birth_date": "1968-10-23", "gender": "non-binary"}, "address": {"street": "2564 Pine Ln", "city": "Vancouver", "zip": "3146", "country": "Canada", "type": "shipping", "state": "BC"}, "preferences": {"newsletter_opt_in": true, "preferred_language": "en", "preferred_currency": "AUD", "marketing_channels": ["postal_mail"], "notification_settings": {"email": true, "sms": false, "push": true}}, "devices": []}');
INSERT INTO customers (customer_id, customer_name, customer_data)
SELECT 1008, 'Harper D''Souza', PARSE_JSON('{"profile": {"first_name": "Harper", "last_name": "D''Souza", "email": "harper.dsouza783@outlook.com", "loyalty_tier": "gold", "join_date": "2023-10-24", "is_active": true, "account_balance": 417.1, "lifetime_value": 534.19, "phone": "+1-669-878-9466", "birth_date": "1975-10-16", "gender": null}, "address": {"street": "2152 Pine Ave", "city": "Seattle", "zip": "78617", "country": "USA", "type": "shipping", "state": "WA", "coordinates": {"lat": 47.6339, "lng": -122.3212}}, "preferences": {"newsletter_opt_in": true, "preferred_language": "es", "preferred_currency": "EUR", "marketing_channels": ["postal_mail"], "notification_settings": {"email": true, "sms": false, "push": false}}, "devices": [{"device_id": "DEV-687513", "device_type": "mobile", "os": "iOS", "last_login": "2026-07-02T06:17:00Z", "is_trusted": false}, {"device_id": "DEV-632376", "device_type": "mobile", "os": "Android", "last_login": "2026-08-11T00:48:00Z", "is_trusted": true}, {"device_id": "DEV-564779", "device_type": "mobile", "os": "Android", "last_login": "2026-08-18T16:38:00Z", "is_trusted": true}]}');
INSERT INTO customers (customer_id, customer_name, customer_data)
SELECT 1009, 'Henry Walker', PARSE_JSON('{"profile": {"first_name": "Henry", "last_name": "Walker", "email": "henry.walker490@yahoo.com", "loyalty_tier": "gold", "join_date": "2023-12-29", "is_active": true, "account_balance": 446.38, "lifetime_value": 1660.58, "phone": "+1-626-324-7428", "birth_date": "2001-03-20", "gender": "female"}, "address": {"street": "3952 River St", "city": "Paris", "zip": "4484", "country": "France", "type": "billing", "state": "Ile-de-France", "coordinates": {"lat": 48.822, "lng": 2.3738}}, "preferences": {"newsletter_opt_in": true, "preferred_language": "es", "preferred_currency": "GBP", "marketing_channels": ["postal_mail"], "notification_settings": {"email": true, "sms": true, "push": false}}, "devices": [{"device_id": "DEV-800273", "device_type": "mobile", "os": "iOS", "last_login": "2026-06-21T22:27:00Z", "is_trusted": true}, {"device_id": "DEV-455589", "device_type": "desktop", "os": "macOS", "last_login": "2026-06-26T11:20:00Z", "is_trusted": false}, {"device_id": "DEV-120429", "device_type": "desktop", "os": "macOS", "last_login": "2026-08-10T14:28:00Z", "is_trusted": true}]}');
INSERT INTO customers (customer_id, customer_name, customer_data)
SELECT 1010, 'Elizabeth Perez', PARSE_JSON('{"profile": {"first_name": "Elizabeth", "last_name": "Perez", "email": "elizabeth.perez525@gmail.com", "loyalty_tier": "bronze", "join_date": "2024-07-01", "is_active": true, "account_balance": 394.18, "lifetime_value": 7774.98, "gender": "female"}, "address": {"street": "2984 Main Ave", "city": "Paris", "zip": "7918", "country": "France", "type": "billing", "coordinates": {"lat": 48.8581, "lng": 2.3517}}, "preferences": {"newsletter_opt_in": false, "preferred_language": "fr", "preferred_currency": "USD", "marketing_channels": ["postal_mail"], "notification_settings": {"email": true, "sms": false, "push": false}}, "devices": []}');
INSERT INTO customers (customer_id, customer_name, customer_data)
SELECT 1011, 'Harper Garcia', PARSE_JSON('{"profile": {"first_name": "Harper", "last_name": "Garcia", "email": "harper.garcia884@gmail.com", "loyalty_tier": "platinum", "join_date": "2021-05-17", "is_active": false, "account_balance": 497.15, "lifetime_value": 3371.19, "phone": "+1-836-332-1707", "birth_date": "1976-11-11", "gender": "male"}, "address": {"street": "1803 Cedar Blvd", "city": "Dallas", "zip": "16603", "country": "USA", "type": "shipping", "state": "TX"}, "preferences": {"newsletter_opt_in": false, "preferred_language": "fr", "preferred_currency": "AUD", "marketing_channels": ["push"], "notification_settings": {"email": true, "sms": true, "push": false}}, "devices": []}');
INSERT INTO customers (customer_id, customer_name, customer_data)
SELECT 1012, 'Harper Williams', PARSE_JSON('{"profile": {"first_name": "Harper", "last_name": "Williams", "email": "harper.williams518@yahoo.com", "loyalty_tier": "platinum", "join_date": "2021-02-07", "is_active": true, "account_balance": 223.53, "lifetime_value": 5283.65, "phone": "+1-872-706-9944", "birth_date": "1997-11-19", "gender": null}, "address": {"street": "8311 Main Ave", "city": "New York", "zip": "40089", "country": "USA", "type": "billing", "state": "NY"}, "preferences": {"newsletter_opt_in": true, "preferred_language": "es", "preferred_currency": "CAD", "marketing_channels": ["email", "postal_mail"], "notification_settings": {"email": false, "sms": true, "push": true}}, "devices": [{"device_id": "DEV-158092", "device_type": "mobile", "os": "iOS", "last_login": "2026-08-25T12:55:00Z", "is_trusted": true}, {"device_id": "DEV-727864", "device_type": "desktop", "os": "Windows", "last_login": "2026-08-28T09:02:00Z", "is_trusted": true}, {"device_id": "DEV-382105", "device_type": "mobile", "os": "Android", "last_login": "2026-06-01T08:23:00Z", "is_trusted": true}]}');
INSERT INTO customers (customer_id, customer_name, customer_data)
SELECT 1013, 'Nadia Lee', PARSE_JSON('{"profile": {"first_name": "Nadia", "last_name": "Lee", "email": "nadia.lee317@yahoo.com", "loyalty_tier": "gold", "join_date": "2021-03-12", "is_active": true, "account_balance": 167.67, "lifetime_value": 716.93, "phone": "+1-871-405-5066", "birth_date": "2004-08-01", "gender": "female"}, "address": {"street": "1498 Main St", "city": "Dallas", "zip": "28856", "country": "USA", "type": "billing", "state": "TX", "coordinates": {"lat": 32.7661, "lng": -96.817}}, "preferences": {"newsletter_opt_in": true, "preferred_language": "en", "preferred_currency": "AUD", "marketing_channels": ["postal_mail"], "notification_settings": {"email": true, "sms": true, "push": false}}, "devices": [{"device_id": "DEV-748761", "device_type": "tablet", "os": "iPadOS", "last_login": "2026-06-06T22:57:00Z", "is_trusted": true}, {"device_id": "DEV-869499", "device_type": "desktop", "os": "Linux", "last_login": "2026-08-04T04:58:00Z", "is_trusted": true}]}');
INSERT INTO customers (customer_id, customer_name, customer_data)
SELECT 1014, 'Priya Johnson', PARSE_JSON('{"profile": {"first_name": "Priya", "last_name": "Johnson", "email": "priya.johnson43@yahoo.com", "loyalty_tier": "gold", "join_date": "2021-06-24", "is_active": true, "account_balance": 188.31, "lifetime_value": 3638.52, "gender": null}, "address": {"street": "4016 Lake Blvd", "city": "Dallas", "zip": "10434", "country": "USA", "type": "billing", "state": "TX", "coordinates": {"lat": 32.8015, "lng": -96.7967}}, "preferences": {"newsletter_opt_in": true, "preferred_language": "pt", "preferred_currency": "USD", "marketing_channels": ["push", "email", "sms"], "notification_settings": {"email": true, "sms": true, "push": false}}, "devices": [{"device_id": "DEV-986603", "device_type": "desktop", "os": "macOS", "last_login": "2026-06-10T15:58:00Z", "is_trusted": true}, {"device_id": "DEV-746944", "device_type": "mobile", "os": "iOS", "last_login": "2026-06-10T19:09:00Z", "is_trusted": true}, {"device_id": "DEV-879319", "device_type": "tablet", "os": "Android", "last_login": "2026-08-19T18:08:00Z", "is_trusted": false}]}');
INSERT INTO customers (customer_id, customer_name, customer_data)
SELECT 1015, 'Noah Dubois', PARSE_JSON('{"profile": {"first_name": "Noah", "last_name": "Dubois", "email": "noah.dubois709@yahoo.com", "loyalty_tier": "platinum", "join_date": "2024-10-08", "is_active": true, "account_balance": 258.27, "lifetime_value": 3744.07, "phone": "+1-321-762-4264", "birth_date": "1969-06-19", "gender": "female"}, "address": {"street": "7758 Maple Blvd", "city": "Austin", "zip": "70158", "country": "USA", "type": "shipping", "state": "TX", "coordinates": {"lat": 30.314, "lng": -97.7482}}, "preferences": {"newsletter_opt_in": false, "preferred_language": "es", "preferred_currency": "EUR", "marketing_channels": [], "notification_settings": {"email": true, "sms": false, "push": true}}, "devices": [{"device_id": "DEV-732674", "device_type": "mobile", "os": "Android", "last_login": "2026-06-15T22:23:00Z", "is_trusted": false}, {"device_id": "DEV-513223", "device_type": "desktop", "os": "Windows", "last_login": "2026-06-21T00:31:00Z", "is_trusted": true}]}');
INSERT INTO customers (customer_id, customer_name, customer_data)
SELECT 1016, 'Matthew N''Diaye', PARSE_JSON('{"profile": {"first_name": "Matthew", "last_name": "N''Diaye", "email": "matthew.ndiaye386@outlook.com", "loyalty_tier": "bronze", "join_date": "2023-05-03", "is_active": true, "account_balance": 0.87, "lifetime_value": 6018.34, "phone": "+1-322-400-1192", "birth_date": "1980-06-06", "gender": "non-binary"}, "address": {"street": "4158 Highland St", "city": "Phoenix", "zip": "61498", "country": "USA", "type": "billing", "state": "AZ", "coordinates": {"lat": 33.4573, "lng": -112.0879}}, "preferences": {"newsletter_opt_in": true, "preferred_language": "fr", "preferred_currency": "USD", "marketing_channels": ["email", "postal_mail"], "notification_settings": {"email": true, "sms": false, "push": true}}, "devices": [{"device_id": "DEV-557431", "device_type": "desktop", "os": "Linux", "last_login": "2026-07-11T06:49:00Z", "is_trusted": true}]}');
INSERT INTO customers (customer_id, customer_name, customer_data)
SELECT 1017, 'William Johnson', PARSE_JSON('{"profile": {"first_name": "William", "last_name": "Johnson", "email": "william.johnson964@yahoo.com", "loyalty_tier": "bronze", "join_date": "2026-02-14", "is_active": false, "account_balance": 366.18, "lifetime_value": 3634.34, "phone": "+1-859-493-8955", "gender": null}, "address": {"street": "2095 Cedar Rd", "city": "Vancouver", "zip": "7797", "country": "Canada", "type": "billing", "state": "BC", "coordinates": {"lat": 49.2583, "lng": -123.0968}}, "preferences": {"newsletter_opt_in": true, "preferred_language": "de", "preferred_currency": "EUR", "marketing_channels": ["postal_mail", "push"], "notification_settings": {"email": true, "sms": false, "push": true}}, "devices": []}');
INSERT INTO customers (customer_id, customer_name, customer_data)
SELECT 1018, 'James Dubois', PARSE_JSON('{"profile": {"first_name": "James", "last_name": "Dubois", "email": "james.dubois778@icloud.com", "loyalty_tier": "platinum", "join_date": "2023-07-17", "is_active": true, "account_balance": 96.2, "lifetime_value": 771.18, "phone": "+1-293-526-4917", "birth_date": "1979-12-07", "gender": null}, "address": {"street": "3321 Maple Rd", "city": "Dallas", "zip": "60179", "country": "USA", "type": "billing", "state": "TX", "coordinates": {"lat": 32.7477, "lng": -96.82}}, "preferences": {"newsletter_opt_in": true, "preferred_language": "de", "preferred_currency": "GBP", "marketing_channels": ["sms", "push"], "notification_settings": {"email": true, "sms": true, "push": true}}, "devices": [{"device_id": "DEV-384185", "device_type": "mobile", "os": "iOS", "last_login": "2026-07-20T12:41:00Z", "is_trusted": true}]}');
INSERT INTO customers (customer_id, customer_name, customer_data)
SELECT 1019, 'Alexander Johnson', PARSE_JSON('{"profile": {"first_name": "Alexander", "last_name": "Johnson", "email": "alexander.johnson727@icloud.com", "loyalty_tier": "platinum", "join_date": "2021-03-08", "is_active": false, "account_balance": 195.76, "lifetime_value": 7418.28, "phone": "+1-679-659-5070", "birth_date": "1984-01-28", "gender": "male"}, "address": {"street": "2539 Cedar Ln", "city": "Phoenix", "zip": "99400", "country": "USA", "type": "shipping", "state": "AZ", "coordinates": {"lat": 33.4706, "lng": -112.0593}}, "preferences": {"newsletter_opt_in": true, "preferred_language": "de", "preferred_currency": "USD", "marketing_channels": [], "notification_settings": {"email": false, "sms": false, "push": true}}, "devices": []}');
INSERT INTO customers (customer_id, customer_name, customer_data)
SELECT 1020, 'Alexander Rodriguez', PARSE_JSON('{"profile": {"first_name": "Alexander", "last_name": "Rodriguez", "email": "alexander.rodriguez448@gmail.com", "loyalty_tier": "bronze", "join_date": "2023-12-18", "is_active": false, "account_balance": 262.22, "lifetime_value": 4683.98, "phone": "+1-428-815-1018", "gender": "non-binary"}, "address": {"street": "7557 Main Blvd", "city": "Austin", "zip": "94485", "country": "USA", "type": "shipping", "state": "TX", "coordinates": {"lat": 30.2407, "lng": -97.7684}}, "preferences": {"newsletter_opt_in": true, "preferred_language": "fr", "preferred_currency": "USD", "marketing_channels": [], "notification_settings": {"email": false, "sms": true, "push": true}}, "devices": []}');
INSERT INTO customers (customer_id, customer_name, customer_data)
SELECT 1021, 'Harper Anderson', PARSE_JSON('{"profile": {"first_name": "Harper", "last_name": "Anderson", "email": "harper.anderson233@icloud.com", "loyalty_tier": "bronze", "join_date": "2026-03-10", "is_active": true, "account_balance": 359.17, "lifetime_value": 2930.44, "phone": "+1-206-499-9271", "gender": null}, "address": {"street": "3293 Main Ave", "city": "London", "zip": "4781", "country": "UK", "type": "billing", "coordinates": {"lat": 51.4869, "lng": -0.0826}}, "preferences": {"newsletter_opt_in": true, "preferred_language": "es", "preferred_currency": "EUR", "marketing_channels": ["postal_mail", "push", "email"], "notification_settings": {"email": true, "sms": false, "push": false}}, "devices": [{"device_id": "DEV-725084", "device_type": "mobile", "os": "iOS", "last_login": "2026-07-24T01:45:00Z", "is_trusted": false}]}');
INSERT INTO customers (customer_id, customer_name, customer_data)
SELECT 1022, 'Matthew Walker', PARSE_JSON('{"profile": {"first_name": "Matthew", "last_name": "Walker", "email": "matthew.walker82@yahoo.com", "loyalty_tier": "gold", "join_date": "2025-02-09", "is_active": true, "account_balance": 326.23, "lifetime_value": 4222.14, "phone": "+1-519-880-7203", "birth_date": "1970-01-29", "gender": "non-binary"}, "address": {"street": "7258 Cedar St", "city": "Denver", "zip": "10376", "country": "USA", "type": "shipping", "state": "CO", "coordinates": {"lat": 39.7243, "lng": -104.9447}}, "preferences": {"newsletter_opt_in": false, "preferred_language": "es", "preferred_currency": "CAD", "marketing_channels": ["push", "sms"], "notification_settings": {"email": false, "sms": true, "push": false}}, "devices": [{"device_id": "DEV-439014", "device_type": "mobile", "os": "Android", "last_login": "2026-07-31T00:40:00Z", "is_trusted": true}, {"device_id": "DEV-903909", "device_type": "tablet", "os": "Android", "last_login": "2026-06-06T12:02:00Z", "is_trusted": true}, {"device_id": "DEV-369500", "device_type": "mobile", "os": "iOS", "last_login": "2026-06-09T19:21:00Z", "is_trusted": true}]}');
INSERT INTO customers (customer_id, customer_name, customer_data)
SELECT 1023, 'Michael Williams', PARSE_JSON('{"profile": {"first_name": "Michael", "last_name": "Williams", "email": "michael.williams707@outlook.com", "loyalty_tier": "gold", "join_date": "2025-03-09", "is_active": true, "account_balance": 360.79, "lifetime_value": 4784.77, "phone": "+1-266-224-4831", "gender": null}, "address": {"street": "6342 Main Rd", "city": "Austin", "zip": "74680", "country": "USA", "type": "shipping", "state": "TX", "coordinates": {"lat": 30.2355, "lng": -97.7128}}, "preferences": {"newsletter_opt_in": true, "preferred_language": "es", "preferred_currency": "AUD", "marketing_channels": ["push"], "notification_settings": {"email": true, "sms": false, "push": true}}, "devices": []}');
INSERT INTO customers (customer_id, customer_name, customer_data)
SELECT 1024, 'Priya Gonzalez', PARSE_JSON('{"profile": {"first_name": "Priya", "last_name": "Gonzalez", "email": "priya.gonzalez254@icloud.com", "loyalty_tier": "bronze", "join_date": "2025-03-22", "is_active": true, "account_balance": 240.84, "lifetime_value": 4379.7, "birth_date": "1972-03-05", "gender": "female"}, "address": {"street": "1192 Main Ln", "city": "Vancouver", "zip": "2377", "country": "Canada", "type": "shipping", "state": "BC"}, "preferences": {"newsletter_opt_in": true, "preferred_language": "de", "preferred_currency": "EUR", "marketing_channels": ["sms"], "notification_settings": {"email": true, "sms": true, "push": true}}, "devices": []}');
INSERT INTO customers (customer_id, customer_name, customer_data)
SELECT 1025, 'Evelyn Jackson', PARSE_JSON('{"profile": {"first_name": "Evelyn", "last_name": "Jackson", "email": "evelyn.jackson382@outlook.com", "loyalty_tier": "gold", "join_date": "2024-03-06", "is_active": true, "account_balance": 123.71, "lifetime_value": 2000.46, "birth_date": "1977-01-03", "gender": null}, "address": {"street": "3094 Highland St", "city": "Austin", "zip": "61913", "country": "USA", "type": "billing", "state": "TX", "coordinates": {"lat": 30.2679, "lng": -97.77}}, "preferences": {"newsletter_opt_in": true, "preferred_language": "de", "preferred_currency": "USD", "marketing_channels": [], "notification_settings": {"email": false, "sms": true, "push": false}}, "devices": [{"device_id": "DEV-142322", "device_type": "desktop", "os": "macOS", "last_login": "2026-06-30T03:03:00Z", "is_trusted": false}, {"device_id": "DEV-303593", "device_type": "tablet", "os": "iPadOS", "last_login": "2026-07-18T16:55:00Z", "is_trusted": false}, {"device_id": "DEV-372575", "device_type": "tablet", "os": "iPadOS", "last_login": "2026-06-14T20:38:00Z", "is_trusted": true}]}');
INSERT INTO customers (customer_id, customer_name, customer_data)
SELECT 1026, 'Emily Wilson', PARSE_JSON('{"profile": {"first_name": "Emily", "last_name": "Wilson", "email": "emily.wilson145@gmail.com", "loyalty_tier": "silver", "join_date": "2023-01-26", "is_active": true, "account_balance": 19.12, "lifetime_value": 5871.22, "phone": "+1-211-535-7700", "birth_date": "1980-04-02", "gender": "male"}, "address": {"street": "5125 Oak Ave", "city": "Los Angeles", "zip": "14124", "country": "USA", "type": "billing", "state": "CA", "coordinates": {"lat": 34.0085, "lng": -118.2836}}, "preferences": {"newsletter_opt_in": false, "preferred_language": "pt", "preferred_currency": "EUR", "marketing_channels": [], "notification_settings": {"email": true, "sms": false, "push": false}}, "devices": [{"device_id": "DEV-422537", "device_type": "tablet", "os": "Android", "last_login": "2026-06-07T09:47:00Z", "is_trusted": true}, {"device_id": "DEV-534194", "device_type": "desktop", "os": "macOS", "last_login": "2026-06-03T11:41:00Z", "is_trusted": false}]}');
INSERT INTO customers (customer_id, customer_name, customer_data)
SELECT 1027, 'Matthew Wilson', PARSE_JSON('{"profile": {"first_name": "Matthew", "last_name": "Wilson", "email": "matthew.wilson434@gmail.com", "loyalty_tier": "bronze", "join_date": "2023-06-09", "is_active": true, "account_balance": 441.42, "lifetime_value": 3714.2, "gender": null}, "address": {"street": "2344 River St", "city": "New York", "zip": "85086", "country": "USA", "type": "billing", "state": "NY", "coordinates": {"lat": 40.68, "lng": -74.0212}}, "preferences": {"newsletter_opt_in": false, "preferred_language": "es", "preferred_currency": "USD", "marketing_channels": [], "notification_settings": {"email": true, "sms": true, "push": true}}, "devices": [{"device_id": "DEV-232802", "device_type": "desktop", "os": "Windows", "last_login": "2026-08-01T10:03:00Z", "is_trusted": true}]}');
INSERT INTO customers (customer_id, customer_name, customer_data)
SELECT 1028, 'Elizabeth Garcia', PARSE_JSON('{"profile": {"first_name": "Elizabeth", "last_name": "Garcia", "email": "elizabeth.garcia878@yahoo.com", "loyalty_tier": "platinum", "join_date": "2024-08-04", "is_active": true, "account_balance": 98.06, "lifetime_value": 3809.99, "phone": "+1-242-609-9485", "gender": "non-binary"}, "address": {"street": "2026 Cedar Ave", "city": "Philadelphia", "zip": "35243", "country": "USA", "type": "shipping", "state": "PA", "coordinates": {"lat": 39.9868, "lng": -75.148}}, "preferences": {"newsletter_opt_in": true, "preferred_language": "fr", "preferred_currency": "USD", "marketing_channels": ["postal_mail", "push", "sms"], "notification_settings": {"email": true, "sms": false, "push": false}}, "devices": [{"device_id": "DEV-485299", "device_type": "tablet", "os": "Android", "last_login": "2026-08-04T14:11:00Z", "is_trusted": false}, {"device_id": "DEV-613279", "device_type": "tablet", "os": "Android", "last_login": "2026-07-01T14:48:00Z", "is_trusted": true}, {"device_id": "DEV-977181", "device_type": "desktop", "os": "Windows", "last_login": "2026-07-31T12:06:00Z", "is_trusted": false}]}');
INSERT INTO customers (customer_id, customer_name, customer_data)
SELECT 1029, 'Emily Robinson', PARSE_JSON('{"profile": {"first_name": "Emily", "last_name": "Robinson", "email": "emily.robinson453@gmail.com", "loyalty_tier": "bronze", "join_date": "2021-07-07", "is_active": true, "account_balance": 41.12, "lifetime_value": 5881.17, "phone": "+1-723-281-1889", "birth_date": "2000-12-27", "gender": null}, "address": {"street": "2241 Maple St", "city": "Toronto", "zip": "2795", "country": "Canada", "type": "shipping", "state": "ON"}, "preferences": {"newsletter_opt_in": true, "preferred_language": "fr", "preferred_currency": "EUR", "marketing_channels": ["email"], "notification_settings": {"email": true, "sms": true, "push": false}}, "devices": [{"device_id": "DEV-388350", "device_type": "tablet", "os": "Android", "last_login": "2026-06-19T08:32:00Z", "is_trusted": true}, {"device_id": "DEV-318442", "device_type": "desktop", "os": "Linux", "last_login": "2026-07-04T19:32:00Z", "is_trusted": false}]}');
INSERT INTO customers (customer_id, customer_name, customer_data)
SELECT 1030, 'Daniel Williams', PARSE_JSON('{"profile": {"first_name": "Daniel", "last_name": "Williams", "email": "daniel.williams166@outlook.com", "loyalty_tier": "gold", "join_date": "2022-01-08", "is_active": true, "account_balance": 84.37, "lifetime_value": 6289.71, "birth_date": "1983-02-06", "gender": "non-binary"}, "address": {"street": "7432 Pine Ln", "city": "San Diego", "zip": "86027", "country": "USA", "type": "shipping", "state": "CA", "coordinates": {"lat": 32.7193, "lng": -117.1254}}, "preferences": {"newsletter_opt_in": true, "preferred_language": "fr", "preferred_currency": "GBP", "marketing_channels": ["push", "postal_mail", "email"], "notification_settings": {"email": true, "sms": true, "push": false}}, "devices": [{"device_id": "DEV-879715", "device_type": "tablet", "os": "iPadOS", "last_login": "2026-07-08T16:16:00Z", "is_trusted": true}]}');

