-- =====================================================================
-- Synthetic seed data for products (Snowflake)
-- Generated rows: 32 products
-- All data is fictional and generated for testing/demo purposes only.
-- =====================================================================

-- switch databse to semi_stracture_db
USE DATABASE SEMI_STRUCTURED_DB;

-- switch to correct schema staging
USE SCHEMA STAGING ;


-- ---------------------------------------------------------------------
-- PRODUCTS
-- ---------------------------------------------------------------------
-- Corrected product seed data for Snowflake
-- Converted VALUES(..., PARSE_JSON(...)) to INSERT ... SELECT ... PARSE_JSON(...)
-- Records: 32

USE DATABASE SEMI_STRUCTURED_DB;
USE SCHEMA STAGING;

INSERT INTO products (product_id, product_data)
SELECT 'PROD-0001', PARSE_JSON('{"specifications": {"category": "Electronics", "brand": "PixelEdge", "color_options": ["White"], "weight_kg": 9.42, "dimensions": {"length": 53.0, "width": 32.3, "height": 5.7, "unit": "cm"}}, "pricing": {"base_price": 342.53, "currency": "USD", "tax_rate": 0.0582, "price_history": [{"date": "2025-04-19", "price": 335.94}, {"date": "2026-07-01", "price": 310.35}]}, "suppliers": [{"supplier_id": "SUP-005", "supplier_name": "Shenzhen Innovate Ltd.", "country": "China", "lead_time_days": 16, "is_primary": true}, {"supplier_id": "SUP-008", "supplier_name": "Sao Paulo Export Group", "country": "Brazil", "lead_time_days": 26, "is_primary": false}, {"supplier_id": "SUP-002", "supplier_name": "EuroGoods Trading Co.", "country": "Germany", "lead_time_days": 42, "is_primary": false}], "reviews": [{"review_id": "REV-PROD-0001-01", "customer_id": 1001, "rating": 2, "comment": null, "review_date": "2025-08-16", "verified_purchase": true}, {"review_id": "REV-PROD-0001-02", "customer_id": 1005, "rating": 3, "comment": "Perfect for everyday use.", "review_date": "2026-07-21", "verified_purchase": true}, {"review_id": "REV-PROD-0001-03", "customer_id": 1021, "rating": 5, "comment": "Decent, but there''s room for improvement.", "review_date": "2026-04-01", "verified_purchase": true}, {"review_id": "REV-PROD-0001-04", "customer_id": 1030, "rating": 5, "comment": null, "review_date": "2026-02-08", "verified_purchase": false}]}');
INSERT INTO products (product_id, product_data)
SELECT 'PROD-0002', PARSE_JSON('{"specifications": {"category": "Home & Kitchen", "brand": "HearthCraft", "color_options": [], "subcategory": "Cookware", "weight_kg": 2.47, "dimensions": {"length": 109.9, "width": 12.9, "height": 49.8, "unit": "cm"}, "material": "Aluminum"}, "pricing": {"base_price": 52.77, "currency": "USD", "tax_rate": 0.0135, "cost_price": 29.13, "price_history": [{"date": "2025-06-28", "price": 51.56}, {"date": "2025-03-07", "price": 48.82}, {"date": "2025-02-19", "price": 57.97}]}, "suppliers": [{"supplier_id": "SUP-008", "supplier_name": "Sao Paulo Export Group", "country": "Brazil", "lead_time_days": 3, "is_primary": true}, {"supplier_id": "SUP-006", "supplier_name": "Atlas Wholesale", "country": "Mexico", "lead_time_days": 27, "is_primary": false}, {"supplier_id": "SUP-005", "supplier_name": "Shenzhen Innovate Ltd.", "country": "China", "lead_time_days": 30, "is_primary": false}], "reviews": [{"review_id": "REV-PROD-0002-01", "customer_id": 1024, "rating": 4, "comment": "Shipping was fast and the quality is solid.", "review_date": "2025-09-24", "verified_purchase": true}, {"review_id": "REV-PROD-0002-02", "customer_id": 1021, "rating": 1, "comment": "Works exactly as described.", "review_date": "2025-11-19", "verified_purchase": true}, {"review_id": "REV-PROD-0002-03", "customer_id": null, "rating": 3, "comment": null, "review_date": "2025-06-27", "verified_purchase": true}, {"review_id": "REV-PROD-0002-04", "customer_id": 1014, "rating": 5, "comment": "Exceeded my expectations, would buy again.", "review_date": "2025-10-30", "verified_purchase": true}]}');
INSERT INTO products (product_id, product_data)
SELECT 'PROD-0003', PARSE_JSON('{"specifications": {"category": "Sportswear", "brand": "PeakForm", "color_options": [], "weight_kg": 13.58, "dimensions": {"length": 101.8, "width": 20.2, "height": 14.4, "unit": "cm"}, "material": "Aluminum"}, "pricing": {"base_price": 125.01, "currency": "USD", "tax_rate": 0.0836, "price_history": [{"date": "2026-07-04", "price": 120.93}, {"date": "2026-06-28", "price": 128.06}, {"date": "2025-01-28", "price": 119.92}]}, "suppliers": [{"supplier_id": "SUP-004", "supplier_name": "Northland Distributors", "country": "Canada", "lead_time_days": 16, "is_primary": true}, {"supplier_id": "SUP-005", "supplier_name": "Shenzhen Innovate Ltd.", "country": "China", "lead_time_days": 28, "is_primary": false}, {"supplier_id": "SUP-003", "supplier_name": "Global Source Partners", "country": "USA", "lead_time_days": 42, "is_primary": false}], "reviews": [{"review_id": "REV-PROD-0003-01", "customer_id": 1006, "rating": 2, "comment": "Great value for the price!", "review_date": "2025-06-14", "verified_purchase": false}, {"review_id": "REV-PROD-0003-02", "customer_id": 1006, "rating": 3, "comment": "Shipping was fast and the quality is solid.", "review_date": "2026-05-25", "verified_purchase": false}, {"review_id": "REV-PROD-0003-03", "customer_id": 1023, "rating": 1, "comment": null, "review_date": "2025-07-05", "verified_purchase": true}]}');
INSERT INTO products (product_id, product_data)
SELECT 'PROD-0004', PARSE_JSON('{"specifications": {"category": "Books", "brand": "Lantern Press", "color_options": ["Gray"], "subcategory": "Reference", "weight_kg": 1.09}, "pricing": {"base_price": 48.56, "currency": "USD", "tax_rate": 0.0824, "discount_percentage": 15}, "suppliers": [{"supplier_id": "SUP-001", "supplier_name": "Pacific Rim Manufacturing", "country": "China", "lead_time_days": 5, "is_primary": true}], "reviews": [{"review_id": "REV-PROD-0004-01", "customer_id": null, "rating": 1, "comment": null, "review_date": "2026-04-20", "verified_purchase": true}, {"review_id": "REV-PROD-0004-02", "customer_id": 1004, "rating": 2, "comment": "Exceeded my expectations, would buy again.", "review_date": "2025-11-11", "verified_purchase": true}, {"review_id": "REV-PROD-0004-03", "customer_id": 1012, "rating": 3, "comment": "Exceeded my expectations, would buy again.", "review_date": "2025-06-25", "verified_purchase": true}, {"review_id": "REV-PROD-0004-04", "customer_id": 1011, "rating": 5, "comment": "Exactly what I needed, no complaints.", "review_date": "2026-01-30", "verified_purchase": true}, {"review_id": "REV-PROD-0004-05", "customer_id": 1001, "rating": 4, "comment": "Great value for the price!", "review_date": "2026-01-10", "verified_purchase": true}]}');
INSERT INTO products (product_id, product_data)
SELECT 'PROD-0005', PARSE_JSON('{"specifications": {"category": "Beauty", "brand": "GlowLab", "color_options": [], "subcategory": "Skincare", "weight_kg": 10.74, "dimensions": {"length": 100.2, "width": 48.1, "height": 24.4, "unit": "cm"}}, "pricing": {"base_price": 35.79, "currency": "USD", "tax_rate": 0.0497, "cost_price": 14.9}, "suppliers": [{"supplier_id": "SUP-008", "supplier_name": "Sao Paulo Export Group", "country": "Brazil", "lead_time_days": 14, "is_primary": true}], "reviews": [{"review_id": "REV-PROD-0005-01", "customer_id": 1027, "rating": 5, "comment": "Exceeded my expectations, would buy again.", "review_date": "2026-03-23", "verified_purchase": true}, {"review_id": "REV-PROD-0005-02", "customer_id": 1007, "rating": 2, "comment": "Arrived slightly damaged, but support fixed it quickly.", "review_date": "2025-08-24", "verified_purchase": false}, {"review_id": "REV-PROD-0005-03", "customer_id": 1003, "rating": 4, "comment": null, "review_date": "2026-03-15", "verified_purchase": true}, {"review_id": "REV-PROD-0005-04", "customer_id": 1012, "rating": 1, "comment": "Perfect for everyday use.", "review_date": "2025-12-20", "verified_purchase": true}, {"review_id": "REV-PROD-0005-05", "customer_id": null, "rating": 4, "comment": null, "review_date": "2025-06-13", "verified_purchase": true}, {"review_id": "REV-PROD-0005-06", "customer_id": 1014, "rating": 5, "comment": "Exactly what I needed, no complaints.", "review_date": "2025-08-27", "verified_purchase": true}]}');
INSERT INTO products (product_id, product_data)
SELECT 'PROD-0006', PARSE_JSON('{"specifications": {"category": "Outdoor", "brand": "SummitGear", "color_options": ["Gray", "Green", "Red", "Black"], "subcategory": "Hiking Gear", "weight_kg": 7.87, "dimensions": {"length": 104.8, "width": 38.8, "height": 45.2, "unit": "cm"}}, "pricing": {"base_price": 75.53, "currency": "USD", "tax_rate": 0.044, "discount_percentage": 10, "cost_price": 33.07}, "suppliers": [{"supplier_id": "SUP-004", "supplier_name": "Northland Distributors", "country": "Canada", "lead_time_days": 20, "is_primary": true}, {"supplier_id": "SUP-005", "supplier_name": "Shenzhen Innovate Ltd.", "country": "China", "lead_time_days": 22, "is_primary": false}, {"supplier_id": "SUP-002", "supplier_name": "EuroGoods Trading Co.", "country": "Germany", "lead_time_days": 42, "is_primary": false}], "reviews": [{"review_id": "REV-PROD-0006-01", "customer_id": 1008, "rating": 3, "comment": "Good product overall, packaging could be better.", "review_date": "2026-02-23", "verified_purchase": true}]}');
INSERT INTO products (product_id, product_data)
SELECT 'PROD-0007', PARSE_JSON('{"specifications": {"category": "Office Supplies", "brand": "OfficeForm", "color_options": ["Green", "Black"], "weight_kg": 9.9, "dimensions": {"length": 27.5, "width": 16.3, "height": 13.6, "unit": "cm"}}, "pricing": {"base_price": 364.31, "currency": "USD", "tax_rate": 0.0283, "price_history": [{"date": "2025-07-31", "price": 390.29}, {"date": "2026-04-21", "price": 312.75}]}, "suppliers": [{"supplier_id": "SUP-007", "supplier_name": "Meridian Supply Chain", "country": "India", "lead_time_days": 17, "is_primary": true}, {"supplier_id": "SUP-006", "supplier_name": "Atlas Wholesale", "country": "Mexico", "lead_time_days": 35, "is_primary": false}], "reviews": [{"review_id": "REV-PROD-0007-01", "customer_id": 1001, "rating": 2, "comment": "Exceeded my expectations, would buy again.", "review_date": "2026-04-06", "verified_purchase": true}, {"review_id": "REV-PROD-0007-02", "customer_id": 1008, "rating": 4, "comment": null, "review_date": "2026-03-21", "verified_purchase": true}, {"review_id": "REV-PROD-0007-03", "customer_id": 1028, "rating": 2, "comment": null, "review_date": "2026-06-05", "verified_purchase": true}, {"review_id": "REV-PROD-0007-04", "customer_id": null, "rating": 5, "comment": "Not as durable as I expected.", "review_date": "2026-05-14", "verified_purchase": false}, {"review_id": "REV-PROD-0007-05", "customer_id": 1014, "rating": 3, "comment": "Exceeded my expectations, would buy again.", "review_date": "2026-04-18", "verified_purchase": true}, {"review_id": "REV-PROD-0007-06", "customer_id": null, "rating": 2, "comment": "Perfect for everyday use.", "review_date": "2026-06-01", "verified_purchase": true}]}');
INSERT INTO products (product_id, product_data)
SELECT 'PROD-0008', PARSE_JSON('{"specifications": {"category": "Furniture", "brand": "UrbanNest", "color_options": ["Blue", "Black", "Red"], "subcategory": "Sofas", "weight_kg": 10.16, "dimensions": {"length": 112.0, "width": 18.7, "height": 53.1, "unit": "cm"}, "material": "Cotton"}, "pricing": {"base_price": 778.05, "currency": "USD", "tax_rate": 0.079, "discount_percentage": 0, "price_history": [{"date": "2025-07-24", "price": 762.34}]}, "suppliers": [{"supplier_id": "SUP-008", "supplier_name": "Sao Paulo Export Group", "country": "Brazil", "lead_time_days": 37, "is_primary": true}], "reviews": [{"review_id": "REV-PROD-0008-01", "customer_id": 1001, "rating": 3, "comment": "Exactly what I needed, no complaints.", "review_date": "2025-11-23", "verified_purchase": true}]}');
INSERT INTO products (product_id, product_data)
SELECT 'PROD-0009', PARSE_JSON('{"specifications": {"category": "Automotive", "brand": "AutoEdge", "color_options": ["Blue"], "subcategory": "Electronics", "weight_kg": 10.96, "dimensions": {"length": 75.6, "width": 52.8, "height": 21.7, "unit": "cm"}}, "pricing": {"base_price": 148.72, "currency": "USD", "tax_rate": 0.0058, "cost_price": 87.53, "price_history": [{"date": "2025-09-29", "price": 130.47}, {"date": "2025-11-07", "price": 153.98}, {"date": "2026-06-24", "price": 162.53}]}, "suppliers": [{"supplier_id": "SUP-008", "supplier_name": "Sao Paulo Export Group", "country": "Brazil", "lead_time_days": 13, "is_primary": true}, {"supplier_id": "SUP-002", "supplier_name": "EuroGoods Trading Co.", "country": "Germany", "lead_time_days": 11, "is_primary": false}], "reviews": [{"review_id": "REV-PROD-0009-01", "customer_id": 1026, "rating": 2, "comment": "Arrived slightly damaged, but support fixed it quickly.", "review_date": "2026-04-25", "verified_purchase": true}, {"review_id": "REV-PROD-0009-02", "customer_id": 1005, "rating": 3, "comment": null, "review_date": "2026-04-24", "verified_purchase": true}, {"review_id": "REV-PROD-0009-03", "customer_id": null, "rating": 4, "comment": "Arrived slightly damaged, but support fixed it quickly.", "review_date": "2025-10-29", "verified_purchase": true}, {"review_id": "REV-PROD-0009-04", "customer_id": 1025, "rating": 4, "comment": "Decent, but there''s room for improvement.", "review_date": "2026-07-07", "verified_purchase": true}, {"review_id": "REV-PROD-0009-05", "customer_id": 1013, "rating": 3, "comment": "Perfect for everyday use.", "review_date": "2026-05-14", "verified_purchase": false}]}');
INSERT INTO products (product_id, product_data)
SELECT 'PROD-0010', PARSE_JSON('{"specifications": {"category": "Electronics", "brand": "TechNova", "color_options": ["Silver", "Blue"], "subcategory": "Audio", "weight_kg": 9.92, "dimensions": {"length": 46.7, "width": 74.7, "height": 68.6, "unit": "cm"}}, "pricing": {"base_price": 177.14, "currency": "USD", "tax_rate": 0.0787, "discount_percentage": 5, "cost_price": 89.2, "price_history": [{"date": "2025-01-12", "price": 159.86}, {"date": "2025-03-15", "price": 179.62}, {"date": "2025-09-14", "price": 177.5}]}, "suppliers": [{"supplier_id": "SUP-003", "supplier_name": "Global Source Partners", "country": "USA", "lead_time_days": 14, "is_primary": true}, {"supplier_id": "SUP-007", "supplier_name": "Meridian Supply Chain", "country": "India", "lead_time_days": 31, "is_primary": false}, {"supplier_id": "SUP-002", "supplier_name": "EuroGoods Trading Co.", "country": "Germany", "lead_time_days": 25, "is_primary": false}], "reviews": [{"review_id": "REV-PROD-0010-01", "customer_id": 1013, "rating": 5, "comment": "Shipping was fast and the quality is solid.", "review_date": "2026-04-09", "verified_purchase": true}, {"review_id": "REV-PROD-0010-02", "customer_id": 1026, "rating": 1, "comment": null, "review_date": "2026-03-08", "verified_purchase": true}, {"review_id": "REV-PROD-0010-03", "customer_id": null, "rating": 2, "comment": "Arrived slightly damaged, but support fixed it quickly.", "review_date": "2026-05-21", "verified_purchase": false}, {"review_id": "REV-PROD-0010-04", "customer_id": 1027, "rating": 4, "comment": null, "review_date": "2026-08-26", "verified_purchase": false}]}');
INSERT INTO products (product_id, product_data)
SELECT 'PROD-0011', PARSE_JSON('{"specifications": {"category": "Home & Kitchen", "brand": "HearthCraft", "color_options": ["Blue"], "subcategory": "Cookware", "weight_kg": 7.32, "dimensions": {"length": 109.1, "width": 57.5, "height": 21.2, "unit": "cm"}}, "pricing": {"base_price": 185.04, "currency": "USD", "tax_rate": 0.057, "discount_percentage": 5, "cost_price": 99.99, "price_history": [{"date": "2025-10-31", "price": 196.17}, {"date": "2026-01-19", "price": 176.98}, {"date": "2025-03-19", "price": 165.63}]}, "suppliers": [{"supplier_id": "SUP-001", "supplier_name": "Pacific Rim Manufacturing", "country": "China", "lead_time_days": 42, "is_primary": true}, {"supplier_id": "SUP-008", "supplier_name": "Sao Paulo Export Group", "country": "Brazil", "lead_time_days": 5, "is_primary": false}], "reviews": [{"review_id": "REV-PROD-0011-01", "customer_id": null, "rating": 3, "comment": "Works exactly as described.", "review_date": "2026-02-17", "verified_purchase": true}, {"review_id": "REV-PROD-0011-02", "customer_id": null, "rating": 2, "comment": "Great value for the price!", "review_date": "2025-09-18", "verified_purchase": true}, {"review_id": "REV-PROD-0011-03", "customer_id": 1011, "rating": 1, "comment": null, "review_date": "2025-12-05", "verified_purchase": true}]}');
INSERT INTO products (product_id, product_data)
SELECT 'PROD-0012', PARSE_JSON('{"specifications": {"category": "Sportswear", "brand": "ActiveCore", "color_options": ["Blue", "Silver"], "subcategory": "Apparel", "weight_kg": 4.46, "dimensions": {"length": 100.2, "width": 35.3, "height": 41.3, "unit": "cm"}}, "pricing": {"base_price": 50.52, "currency": "USD", "tax_rate": 0.0481, "discount_percentage": 15, "cost_price": 25.22}, "suppliers": [{"supplier_id": "SUP-003", "supplier_name": "Global Source Partners", "country": "USA", "lead_time_days": 43, "is_primary": true}, {"supplier_id": "SUP-005", "supplier_name": "Shenzhen Innovate Ltd.", "country": "China", "lead_time_days": 8, "is_primary": false}], "reviews": [{"review_id": "REV-PROD-0012-01", "customer_id": 1024, "rating": 5, "comment": "Perfect for everyday use.", "review_date": "2026-03-07", "verified_purchase": true}, {"review_id": "REV-PROD-0012-02", "customer_id": 1004, "rating": 1, "comment": "Great value for the price!", "review_date": "2025-09-06", "verified_purchase": true}, {"review_id": "REV-PROD-0012-03", "customer_id": 1025, "rating": 1, "comment": "Exactly what I needed, no complaints.", "review_date": "2026-03-06", "verified_purchase": true}, {"review_id": "REV-PROD-0012-04", "customer_id": 1021, "rating": 5, "comment": null, "review_date": "2025-07-13", "verified_purchase": false}]}');
INSERT INTO products (product_id, product_data)
SELECT 'PROD-0013', PARSE_JSON('{"specifications": {"category": "Books", "brand": "Northwind Publishing", "color_options": [], "subcategory": "Fiction", "weight_kg": 0.62}, "pricing": {"base_price": 48.61, "currency": "USD", "tax_rate": 0.0884, "cost_price": 21.47}, "suppliers": [{"supplier_id": "SUP-005", "supplier_name": "Shenzhen Innovate Ltd.", "country": "China", "lead_time_days": 14, "is_primary": true}, {"supplier_id": "SUP-007", "supplier_name": "Meridian Supply Chain", "country": "India", "lead_time_days": 29, "is_primary": false}, {"supplier_id": "SUP-003", "supplier_name": "Global Source Partners", "country": "USA", "lead_time_days": 5, "is_primary": false}], "reviews": [{"review_id": "REV-PROD-0013-01", "customer_id": 1021, "rating": 5, "comment": "Great value for the price!", "review_date": "2026-02-10", "verified_purchase": true}, {"review_id": "REV-PROD-0013-02", "customer_id": 1004, "rating": 4, "comment": "Good product overall, packaging could be better.", "review_date": "2026-05-23", "verified_purchase": true}]}');
INSERT INTO products (product_id, product_data)
SELECT 'PROD-0014', PARSE_JSON('{"specifications": {"category": "Beauty", "brand": "PureDerm", "color_options": ["Red", "Gray", "White"], "subcategory": "Suncare", "weight_kg": 8.28, "dimensions": {"length": 14.5, "width": 40.4, "height": 71.9, "unit": "cm"}, "material": "Cotton"}, "pricing": {"base_price": 10.78, "currency": "USD", "tax_rate": 0.0005, "discount_percentage": 0, "cost_price": 7.09}, "suppliers": [{"supplier_id": "SUP-003", "supplier_name": "Global Source Partners", "country": "USA", "lead_time_days": 33, "is_primary": true}], "reviews": []}');
INSERT INTO products (product_id, product_data)
SELECT 'PROD-0015', PARSE_JSON('{"specifications": {"category": "Outdoor", "brand": "SummitGear", "color_options": ["Black"], "subcategory": "Camping", "weight_kg": 10.97, "dimensions": {"length": 14.7, "width": 52.1, "height": 57.3, "unit": "cm"}}, "pricing": {"base_price": 245.4, "currency": "USD", "tax_rate": 0.0886, "cost_price": 150.96}, "suppliers": [{"supplier_id": "SUP-002", "supplier_name": "EuroGoods Trading Co.", "country": "Germany", "lead_time_days": 27, "is_primary": true}], "reviews": [{"review_id": "REV-PROD-0015-01", "customer_id": null, "rating": 2, "comment": "Arrived slightly damaged, but support fixed it quickly.", "review_date": "2026-04-08", "verified_purchase": false}, {"review_id": "REV-PROD-0015-02", "customer_id": 1019, "rating": 4, "comment": "Arrived slightly damaged, but support fixed it quickly.", "review_date": "2026-05-13", "verified_purchase": false}]}');
INSERT INTO products (product_id, product_data)
SELECT 'PROD-0016', PARSE_JSON('{"specifications": {"category": "Office Supplies", "brand": "OfficeForm", "color_options": ["Green"], "subcategory": "Desks", "weight_kg": 5.85, "dimensions": {"length": 95.4, "width": 75.9, "height": 63.2, "unit": "cm"}, "material": "Stainless Steel"}, "pricing": {"base_price": 363.63, "currency": "USD", "tax_rate": 0.0266, "discount_percentage": 20, "price_history": [{"date": "2025-06-04", "price": 363.73}]}, "suppliers": [{"supplier_id": "SUP-007", "supplier_name": "Meridian Supply Chain", "country": "India", "lead_time_days": 27, "is_primary": true}, {"supplier_id": "SUP-002", "supplier_name": "EuroGoods Trading Co.", "country": "Germany", "lead_time_days": 27, "is_primary": false}], "reviews": [{"review_id": "REV-PROD-0016-01", "customer_id": 1029, "rating": 2, "comment": "Arrived slightly damaged, but support fixed it quickly.", "review_date": "2025-10-24", "verified_purchase": true}, {"review_id": "REV-PROD-0016-02", "customer_id": 1009, "rating": 4, "comment": "Shipping was fast and the quality is solid.", "review_date": "2026-03-28", "verified_purchase": true}, {"review_id": "REV-PROD-0016-03", "customer_id": null, "rating": 1, "comment": "Exceeded my expectations, would buy again.", "review_date": "2026-08-01", "verified_purchase": false}]}');
INSERT INTO products (product_id, product_data)
SELECT 'PROD-0017', PARSE_JSON('{"specifications": {"category": "Furniture", "brand": "UrbanNest", "color_options": ["Green", "Blue", "Silver", "Black"], "subcategory": "Seating", "weight_kg": 11.98, "dimensions": {"length": 28.0, "width": 61.3, "height": 74.7, "unit": "cm"}}, "pricing": {"base_price": 880.05, "currency": "USD", "tax_rate": 0.0577, "discount_percentage": 15, "cost_price": 596.5, "price_history": [{"date": "2026-01-30", "price": 849.19}]}, "suppliers": [{"supplier_id": "SUP-006", "supplier_name": "Atlas Wholesale", "country": "Mexico", "lead_time_days": 7, "is_primary": true}], "reviews": [{"review_id": "REV-PROD-0017-01", "customer_id": 1029, "rating": 3, "comment": "Exactly what I needed, no complaints.", "review_date": "2025-11-12", "verified_purchase": true}]}');
INSERT INTO products (product_id, product_data)
SELECT 'PROD-0018', PARSE_JSON('{"specifications": {"category": "Automotive", "brand": "DriveTech", "color_options": [], "weight_kg": 10.55, "dimensions": {"length": 46.7, "width": 47.3, "height": 33.4, "unit": "cm"}, "material": "Aluminum"}, "pricing": {"base_price": 46.08, "currency": "USD", "tax_rate": 0.0234, "discount_percentage": 15}, "suppliers": [{"supplier_id": "SUP-008", "supplier_name": "Sao Paulo Export Group", "country": "Brazil", "lead_time_days": 12, "is_primary": true}, {"supplier_id": "SUP-007", "supplier_name": "Meridian Supply Chain", "country": "India", "lead_time_days": 23, "is_primary": false}, {"supplier_id": "SUP-001", "supplier_name": "Pacific Rim Manufacturing", "country": "China", "lead_time_days": 41, "is_primary": false}], "reviews": []}');
INSERT INTO products (product_id, product_data)
SELECT 'PROD-0019', PARSE_JSON('{"specifications": {"category": "Electronics", "brand": "PixelEdge", "color_options": ["Gray"], "subcategory": "Storage", "weight_kg": 8.84, "dimensions": {"length": 29.6, "width": 74.4, "height": 23.8, "unit": "cm"}}, "pricing": {"base_price": 64.99, "currency": "USD", "tax_rate": 0.0425, "discount_percentage": 20, "cost_price": 30.95}, "suppliers": [{"supplier_id": "SUP-003", "supplier_name": "Global Source Partners", "country": "USA", "lead_time_days": 27, "is_primary": true}], "reviews": []}');
INSERT INTO products (product_id, product_data)
SELECT 'PROD-0020', PARSE_JSON('{"specifications": {"category": "Home & Kitchen", "brand": "HearthCraft", "color_options": ["Blue", "Black", "Red"], "subcategory": "Cookware", "weight_kg": 10.63, "dimensions": {"length": 15.3, "width": 28.9, "height": 20.2, "unit": "cm"}}, "pricing": {"base_price": 236.23, "currency": "USD", "tax_rate": 0.0875, "discount_percentage": 5, "cost_price": 105.81, "price_history": [{"date": "2025-08-16", "price": 210.96}, {"date": "2025-09-20", "price": 256.38}, {"date": "2025-03-02", "price": 254.11}]}, "suppliers": [{"supplier_id": "SUP-001", "supplier_name": "Pacific Rim Manufacturing", "country": "China", "lead_time_days": 19, "is_primary": true}], "reviews": [{"review_id": "REV-PROD-0020-01", "customer_id": null, "rating": 4, "comment": "Great value for the price!", "review_date": "2025-07-22", "verified_purchase": false}, {"review_id": "REV-PROD-0020-02", "customer_id": null, "rating": 2, "comment": null, "review_date": "2026-06-19", "verified_purchase": true}, {"review_id": "REV-PROD-0020-03", "customer_id": 1025, "rating": 1, "comment": "Arrived slightly damaged, but support fixed it quickly.", "review_date": "2025-11-13", "verified_purchase": true}, {"review_id": "REV-PROD-0020-04", "customer_id": 1012, "rating": 4, "comment": "Perfect for everyday use.", "review_date": "2025-08-26", "verified_purchase": true}]}');
INSERT INTO products (product_id, product_data)
SELECT 'PROD-0021', PARSE_JSON('{"specifications": {"category": "Sportswear", "brand": "PeakForm", "color_options": ["Gray"], "weight_kg": 13.92, "dimensions": {"length": 30.4, "width": 75.0, "height": 69.6, "unit": "cm"}, "material": "Aluminum"}, "pricing": {"base_price": 73.49, "currency": "USD", "tax_rate": 0.0739, "discount_percentage": 15, "cost_price": 43.25}, "suppliers": [{"supplier_id": "SUP-006", "supplier_name": "Atlas Wholesale", "country": "Mexico", "lead_time_days": 17, "is_primary": true}, {"supplier_id": "SUP-007", "supplier_name": "Meridian Supply Chain", "country": "India", "lead_time_days": 33, "is_primary": false}], "reviews": []}');
INSERT INTO products (product_id, product_data)
SELECT 'PROD-0022', PARSE_JSON('{"specifications": {"category": "Books", "brand": "Northwind Publishing", "color_options": [], "weight_kg": 0.65, "material": "Cotton"}, "pricing": {"base_price": 27.93, "currency": "USD", "tax_rate": 0.0827, "cost_price": 12.48}, "suppliers": [{"supplier_id": "SUP-006", "supplier_name": "Atlas Wholesale", "country": "Mexico", "lead_time_days": 13, "is_primary": true}, {"supplier_id": "SUP-007", "supplier_name": "Meridian Supply Chain", "country": "India", "lead_time_days": 19, "is_primary": false}], "reviews": [{"review_id": "REV-PROD-0022-01", "customer_id": 1029, "rating": 4, "comment": "Works exactly as described.", "review_date": "2025-08-18", "verified_purchase": true}, {"review_id": "REV-PROD-0022-02", "customer_id": 1029, "rating": 2, "comment": "Exactly what I needed, no complaints.", "review_date": "2026-01-31", "verified_purchase": true}]}');
INSERT INTO products (product_id, product_data)
SELECT 'PROD-0023', PARSE_JSON('{"specifications": {"category": "Beauty", "brand": "GlowLab", "color_options": ["Blue", "Silver"], "subcategory": "Skincare", "weight_kg": 1.55, "dimensions": {"length": 38.3, "width": 72.2, "height": 6.5, "unit": "cm"}, "material": "Stainless Steel"}, "pricing": {"base_price": 51.52, "currency": "USD", "tax_rate": 0.0137, "discount_percentage": 15, "cost_price": 25.88}, "suppliers": [{"supplier_id": "SUP-005", "supplier_name": "Shenzhen Innovate Ltd.", "country": "China", "lead_time_days": 14, "is_primary": true}], "reviews": [{"review_id": "REV-PROD-0023-01", "customer_id": 1014, "rating": 2, "comment": "Exceeded my expectations, would buy again.", "review_date": "2026-03-20", "verified_purchase": false}, {"review_id": "REV-PROD-0023-02", "customer_id": null, "rating": 5, "comment": "Not as durable as I expected.", "review_date": "2026-05-31", "verified_purchase": false}]}');
INSERT INTO products (product_id, product_data)
SELECT 'PROD-0024', PARSE_JSON('{"specifications": {"category": "Outdoor", "brand": "SummitGear", "color_options": ["Gray", "Silver", "White"], "weight_kg": 9.23, "dimensions": {"length": 86.4, "width": 65.9, "height": 47.5, "unit": "cm"}}, "pricing": {"base_price": 289.01, "currency": "USD", "tax_rate": 0.0062, "discount_percentage": 15, "cost_price": 195.05, "price_history": [{"date": "2025-12-10", "price": 266.02}, {"date": "2026-05-20", "price": 252.19}]}, "suppliers": [{"supplier_id": "SUP-008", "supplier_name": "Sao Paulo Export Group", "country": "Brazil", "lead_time_days": 45, "is_primary": true}, {"supplier_id": "SUP-002", "supplier_name": "EuroGoods Trading Co.", "country": "Germany", "lead_time_days": 20, "is_primary": false}], "reviews": [{"review_id": "REV-PROD-0024-01", "customer_id": 1012, "rating": 1, "comment": "Shipping was fast and the quality is solid.", "review_date": "2026-05-26", "verified_purchase": true}]}');
INSERT INTO products (product_id, product_data)
SELECT 'PROD-0025', PARSE_JSON('{"specifications": {"category": "Office Supplies", "brand": "OfficeForm", "color_options": ["Red", "Black", "Green"], "subcategory": "Seating", "weight_kg": 12.27, "dimensions": {"length": 104.5, "width": 29.1, "height": 57.5, "unit": "cm"}}, "pricing": {"base_price": 209.54, "currency": "USD", "tax_rate": 0.0714, "cost_price": 143.79}, "suppliers": [{"supplier_id": "SUP-001", "supplier_name": "Pacific Rim Manufacturing", "country": "China", "lead_time_days": 11, "is_primary": true}, {"supplier_id": "SUP-005", "supplier_name": "Shenzhen Innovate Ltd.", "country": "China", "lead_time_days": 4, "is_primary": false}, {"supplier_id": "SUP-007", "supplier_name": "Meridian Supply Chain", "country": "India", "lead_time_days": 18, "is_primary": false}], "reviews": [{"review_id": "REV-PROD-0025-01", "customer_id": 1006, "rating": 2, "comment": "Works exactly as described.", "review_date": "2025-11-07", "verified_purchase": true}, {"review_id": "REV-PROD-0025-02", "customer_id": null, "rating": 1, "comment": "Great value for the price!", "review_date": "2025-07-20", "verified_purchase": true}, {"review_id": "REV-PROD-0025-03", "customer_id": null, "rating": 3, "comment": "Great value for the price!", "review_date": "2026-08-03", "verified_purchase": true}, {"review_id": "REV-PROD-0025-04", "customer_id": 1017, "rating": 2, "comment": null, "review_date": "2026-01-14", "verified_purchase": false}, {"review_id": "REV-PROD-0025-05", "customer_id": null, "rating": 2, "comment": "Great value for the price!", "review_date": "2025-10-18", "verified_purchase": false}, {"review_id": "REV-PROD-0025-06", "customer_id": 1017, "rating": 3, "comment": "Works exactly as described.", "review_date": "2025-08-02", "verified_purchase": false}]}');
INSERT INTO products (product_id, product_data)
SELECT 'PROD-0026', PARSE_JSON('{"specifications": {"category": "Furniture", "brand": "UrbanNest", "color_options": ["White"], "subcategory": "Seating", "weight_kg": 11.22, "dimensions": {"length": 23.9, "width": 67.0, "height": 75.1, "unit": "cm"}}, "pricing": {"base_price": 569.37, "currency": "USD", "tax_rate": 0.0399, "discount_percentage": 20, "price_history": [{"date": "2026-01-07", "price": 532.15}]}, "suppliers": [{"supplier_id": "SUP-006", "supplier_name": "Atlas Wholesale", "country": "Mexico", "lead_time_days": 30, "is_primary": true}], "reviews": [{"review_id": "REV-PROD-0026-01", "customer_id": 1030, "rating": 3, "comment": "Perfect for everyday use.", "review_date": "2026-08-08", "verified_purchase": true}, {"review_id": "REV-PROD-0026-02", "customer_id": 1005, "rating": 3, "comment": "Not as durable as I expected.", "review_date": "2026-08-20", "verified_purchase": true}, {"review_id": "REV-PROD-0026-03", "customer_id": 1012, "rating": 1, "comment": "Exactly what I needed, no complaints.", "review_date": "2025-09-04", "verified_purchase": false}, {"review_id": "REV-PROD-0026-04", "customer_id": 1017, "rating": 1, "comment": "Not as durable as I expected.", "review_date": "2025-08-11", "verified_purchase": true}]}');
INSERT INTO products (product_id, product_data)
SELECT 'PROD-0027', PARSE_JSON('{"specifications": {"category": "Automotive", "brand": "AutoEdge", "color_options": [], "weight_kg": 9.66, "dimensions": {"length": 35.6, "width": 55.9, "height": 23.3, "unit": "cm"}, "material": "Plastic"}, "pricing": {"base_price": 101.58, "currency": "USD", "tax_rate": 0.059, "cost_price": 53.85, "price_history": [{"date": "2025-04-26", "price": 94.1}, {"date": "2025-06-20", "price": 89.4}]}, "suppliers": [{"supplier_id": "SUP-005", "supplier_name": "Shenzhen Innovate Ltd.", "country": "China", "lead_time_days": 40, "is_primary": true}, {"supplier_id": "SUP-001", "supplier_name": "Pacific Rim Manufacturing", "country": "China", "lead_time_days": 37, "is_primary": false}, {"supplier_id": "SUP-004", "supplier_name": "Northland Distributors", "country": "Canada", "lead_time_days": 12, "is_primary": false}], "reviews": [{"review_id": "REV-PROD-0027-01", "customer_id": 1029, "rating": 3, "comment": "Perfect for everyday use.", "review_date": "2026-03-23", "verified_purchase": true}, {"review_id": "REV-PROD-0027-02", "customer_id": 1003, "rating": 5, "comment": "Exceeded my expectations, would buy again.", "review_date": "2026-08-04", "verified_purchase": true}]}');
INSERT INTO products (product_id, product_data)
SELECT 'PROD-0028', PARSE_JSON('{"specifications": {"category": "Electronics", "brand": "SoundWave", "color_options": ["Blue", "Red"], "subcategory": "Storage", "weight_kg": 7.09, "dimensions": {"length": 40.7, "width": 23.2, "height": 19.3, "unit": "cm"}, "material": "Cotton"}, "pricing": {"base_price": 110.51, "currency": "USD", "tax_rate": 0.0921, "cost_price": 49.58, "price_history": [{"date": "2026-07-25", "price": 102.93}, {"date": "2025-10-04", "price": 101.8}]}, "suppliers": [{"supplier_id": "SUP-005", "supplier_name": "Shenzhen Innovate Ltd.", "country": "China", "lead_time_days": 6, "is_primary": true}], "reviews": [{"review_id": "REV-PROD-0028-01", "customer_id": 1003, "rating": 5, "comment": "Decent, but there''s room for improvement.", "review_date": "2026-01-12", "verified_purchase": true}, {"review_id": "REV-PROD-0028-02", "customer_id": 1027, "rating": 4, "comment": "Decent, but there''s room for improvement.", "review_date": "2026-06-12", "verified_purchase": true}, {"review_id": "REV-PROD-0028-03", "customer_id": 1022, "rating": 2, "comment": "Perfect for everyday use.", "review_date": "2025-11-20", "verified_purchase": true}, {"review_id": "REV-PROD-0028-04", "customer_id": 1007, "rating": 5, "comment": "Good product overall, packaging could be better.", "review_date": "2026-08-10", "verified_purchase": true}]}');
INSERT INTO products (product_id, product_data)
SELECT 'PROD-0029', PARSE_JSON('{"specifications": {"category": "Home & Kitchen", "brand": "HomeEase", "color_options": ["Silver", "Green", "White"], "subcategory": "Cookware", "weight_kg": 0.16, "dimensions": {"length": 93.1, "width": 48.9, "height": 40.8, "unit": "cm"}, "material": "Wood"}, "pricing": {"base_price": 303.34, "currency": "USD", "tax_rate": 0.0142, "discount_percentage": 10, "cost_price": 176.6}, "suppliers": [{"supplier_id": "SUP-008", "supplier_name": "Sao Paulo Export Group", "country": "Brazil", "lead_time_days": 25, "is_primary": true}, {"supplier_id": "SUP-003", "supplier_name": "Global Source Partners", "country": "USA", "lead_time_days": 21, "is_primary": false}], "reviews": [{"review_id": "REV-PROD-0029-01", "customer_id": 1020, "rating": 4, "comment": null, "review_date": "2025-11-12", "verified_purchase": false}, {"review_id": "REV-PROD-0029-02", "customer_id": null, "rating": 4, "comment": "Perfect for everyday use.", "review_date": "2026-01-14", "verified_purchase": true}]}');
INSERT INTO products (product_id, product_data)
SELECT 'PROD-0030', PARSE_JSON('{"specifications": {"category": "Sportswear", "brand": "ActiveCore", "color_options": ["Red", "Blue", "Gray"], "weight_kg": 12.34, "dimensions": {"length": 43.0, "width": 77.7, "height": 49.4, "unit": "cm"}}, "pricing": {"base_price": 115.37, "currency": "USD", "tax_rate": 0.031, "discount_percentage": 0}, "suppliers": [{"supplier_id": "SUP-005", "supplier_name": "Shenzhen Innovate Ltd.", "country": "China", "lead_time_days": 22, "is_primary": true}, {"supplier_id": "SUP-008", "supplier_name": "Sao Paulo Export Group", "country": "Brazil", "lead_time_days": 37, "is_primary": false}], "reviews": [{"review_id": "REV-PROD-0030-01", "customer_id": 1027, "rating": 5, "comment": null, "review_date": "2026-05-17", "verified_purchase": true}, {"review_id": "REV-PROD-0030-02", "customer_id": 1002, "rating": 5, "comment": null, "review_date": "2025-11-27", "verified_purchase": true}, {"review_id": "REV-PROD-0030-03", "customer_id": 1003, "rating": 5, "comment": "Not as durable as I expected.", "review_date": "2025-07-21", "verified_purchase": true}]}');
INSERT INTO products (product_id, product_data)
SELECT 'PROD-0031', PARSE_JSON('{"specifications": {"category": "Books", "brand": "Northwind Publishing", "color_options": ["White", "Gray", "Blue", "Red"], "subcategory": "Reference", "weight_kg": 1.1, "material": "Glass"}, "pricing": {"base_price": 38.94, "currency": "USD", "tax_rate": 0.0504, "discount_percentage": 5}, "suppliers": [{"supplier_id": "SUP-005", "supplier_name": "Shenzhen Innovate Ltd.", "country": "China", "lead_time_days": 35, "is_primary": true}], "reviews": [{"review_id": "REV-PROD-0031-01", "customer_id": 1010, "rating": 3, "comment": "Exactly what I needed, no complaints.", "review_date": "2026-08-29", "verified_purchase": true}]}');
INSERT INTO products (product_id, product_data)
SELECT 'PROD-0032', PARSE_JSON('{"specifications": {"category": "Beauty", "brand": "GlowLab", "color_options": ["White", "Red", "Gray", "Blue"], "weight_kg": 9.49, "dimensions": {"length": 74.4, "width": 31.5, "height": 79.5, "unit": "cm"}, "material": "Plastic"}, "pricing": {"base_price": 25.95, "currency": "USD", "tax_rate": 0.0657, "price_history": [{"date": "2025-01-05", "price": 28.01}, {"date": "2026-02-12", "price": 27.52}, {"date": "2026-08-24", "price": 22.16}]}, "suppliers": [{"supplier_id": "SUP-004", "supplier_name": "Northland Distributors", "country": "Canada", "lead_time_days": 14, "is_primary": true}], "reviews": [{"review_id": "REV-PROD-0032-01", "customer_id": 1009, "rating": 5, "comment": "Exactly what I needed, no complaints.", "review_date": "2025-08-13", "verified_purchase": true}, {"review_id": "REV-PROD-0032-02", "customer_id": 1004, "rating": 2, "comment": "Shipping was fast and the quality is solid.", "review_date": "2026-02-21", "verified_purchase": true}]}');